version: '3'

services:
  multisigwallet:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
    image: multisigwallet
    container_name: multisigwallet
    network_mode: "host"
    hostname: multisigwallet
    ports:
      - "127.0.0.1:8282:8282/tcp"

